### Loading an Image & Information gathering

In [1]:
import cv2

In [2]:
image = cv2.imread('./images/A-Cat.jpg')

In [3]:
print(image)
image.dtype

[[[179 194 213]
  [175 190 209]
  [174 189 208]
  ...
  [179 185 174]
  [178 184 173]
  [178 184 173]]

 [[178 193 212]
  [176 191 210]
  [175 190 209]
  ...
  [179 185 174]
  [178 184 173]
  [177 183 172]]

 [[178 193 212]
  [176 191 210]
  [176 191 210]
  ...
  [179 184 175]
  [180 184 173]
  [179 183 172]]

 ...

 [[163 180 213]
  [163 180 213]
  [163 180 213]
  ...
  [ 57  24   4]
  [ 58  23   3]
  [ 56  21   1]]

 [[163 180 213]
  [163 180 213]
  [163 180 213]
  ...
  [ 58  25   5]
  [ 59  24   4]
  [ 57  22   2]]

 [[163 180 213]
  [163 180 213]
  [163 180 213]
  ...
  [ 62  27   7]
  [ 60  25   5]
  [ 59  24   4]]]


dtype('uint8')

In [4]:
image.shape

(2571, 3840, 3)

In [5]:
image2 = [
  # Row 0: Top line of pixels
  [[255, 0, 0],   [0, 255, 0],   [0, 0, 255]], 
  
  # Row 1: Middle line of pixels
  [[255, 0, 0],   [0, 255, 0],   [0, 0, 255]], 
  
  # Row 2: Bottom line of pixels
  [[255, 0, 0],   [0, 255, 0],   [0, 0, 255]]
]

In [6]:
min(image2)

[[255, 0, 0], [0, 255, 0], [0, 0, 255]]

In [7]:
image.min()

np.uint8(0)

In [ ]:
cv2.imshow('frame', image) # opens an image in a window named 'frame'
cv2.waitKey(0) # waits for a key press to close the window, 0 means wait indefinitely (it does not work in Jupyter notebooks, use in a .py file)
cv2.destroyAllWindows() # closes all windows (it does not work in Jupyter notebooks, use in a .py file)

: 

In [8]:
grey_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) # converts the image to grayscale
cv2.imwrite('./images/A-Cat-Grey.jpg', grey_image) 

True

In [9]:
# cv2.resize(image, (width, height))
resized_image = cv2.resize(image, (900, 500)) # resizes the image to 900x500 pixels
cv2.imwrite('./images/A-Cat-Resized.jpg', resized_image)

True

In [10]:
# image[height_start:height_end, width_start:width_end]
cropped_image = image[700:1500, 700:2500] # crops the image to the region of interest (ROI) defined by the pixel coordinates (y1:y2, x1:x2)
cv2.imwrite('./images/A-Cat-Cropped.jpg', cropped_image)

True

In [11]:
rotated_image = cv2.rotate(image, cv2.ROTATE_90_CLOCKWISE) # rotates the image 90 degrees clockwise
cv2.imwrite('./images/A-Cat-Rotated.jpg', rotated_image)

True

In [12]:
# custom rotation
(h, w) = image.shape[:2]
center = (w // 2, h // 2)
point = (w // 4 + 100, h // 3 + 100)

# matrix = cv2.getRotationMatrix2D(center, 45, 1)
matrix = cv2.getRotationMatrix2D(point, 55, 0.5)
custom_rotated_image = cv2.warpAffine(image, matrix, (w, h))
cv2.imwrite('./images/A-Cat-Custom-Rotated.jpg', custom_rotated_image)

True

In [14]:
#flip
flipped_image = cv2.flip(image, -1) # flips the image horizontally (1 for horizontal, 0 for vertical, -1 for both)
cv2.imwrite('./images/A-Cat-Flipped.jpg', flipped_image)

True