# LAB1: NumPy Exercises 


#### Import NumPy as np

In [126]:
import numpy as np

#### Create an array of 10 zeros 

In [127]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [128]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [129]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [130]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [131]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [132]:
arr = np.arange(0, 9)
arr.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Use NumPy to generate a random number between 0 and 1

In [133]:
np.random.rand()

0.31046253957179426

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [134]:
np.random.randn(25)

array([ 0.03344191,  0.14616793,  0.0874113 , -0.4199272 , -0.08218309,
       -0.60312586, -0.44501903, -2.16527178,  0.28873943, -1.34275931,
        1.62830065, -2.00509995,  0.68369688,  0.90081143, -0.94805629,
        0.22647099,  1.33182095,  0.10082299, -0.26484022,  0.25912848,
       -1.09503261, -0.86645954, -0.77812797, -0.23056244, -0.8139134 ])

#### Create the following matrix:

In [135]:
np.arange(0.01, 1.01, 0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [136]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [137]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Write a code that creates the following output**

In [138]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [139]:
mat[3, 4]

np.int64(20)

In [140]:
mat[:3, 1:2] # mat[:3, 1] drops the dimention

array([[ 2],
       [ 7],
       [12]])

In [141]:
mat[4]

array([21, 22, 23, 24, 25])

In [142]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [143]:
mat.sum()

np.int64(325)

#### Get the sum of all the columns in mat

In [144]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

#### Broadcasting

Given a=np.arange(3).reshape(3, 1) and b=np.arange(3):

- Predict the result of a + b without running the code.
    + It's going to be a 3x3 matrix as NumPy will apply broadcasting:
      [
        [0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
      ]

- Explain the broadcasting rules at play.
    + It compares the shape of a and b from right to left and here a's shape is 2D (3,1) but b's shape is 1D (3,).
    + Numpy will now expand b to treat as (1, 3). 
    + Two dimentions are only compatible:
        - They are same/equal OR one of them is 1.


- Create the arrays and run the results
    + array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

- Implement a solution that would not rely on broadcasting (using np.tile or similar).
    ```python
    a_without_broadcating = np.tile(a, (1,3))
    b_without_broadcating = np.tile(b, (3,1))

    a_without_broadcating+b_without_broadcating
    ```

In [145]:
# With broadcasting
a = np.arange(3).reshape(3,1) 
b = np.arange(3)

a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [146]:
# Without broadcasting (with np.tile())
a_without_broadcating = np.tile(a, (1,3))
b_without_broadcating = np.tile(b, (3,1)) # np.tile() repeats an array multiple times to create a larger array/matrix of perticular shape.

a_without_broadcating+b_without_broadcating

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Great Job!